# DEV Environment

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jobhunterTest}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update

# Mail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App config
app.base-url=${APP_BASE_URL:http://localhost:8080}
app.reset-token-expiry-minutes=30

# Log level
logging.level.com.jobhunter=DEBUG
logging.level.org.springframework.security=DEBUG

app.upload.cv-dir=uploads/cv
app.upload.logo-dir=uploads/logo